version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  parc-sauvage:
    build:
      context: ./parcSauvage
      dockerfile: ./parcSauvage/ops/Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./parcSauvage:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/parcSauvage

  parc-touristique:
    build:
      context: ./parcTouristique
      dockerfile: parcTouristique/ops/Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./parcTouristique:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/parcTouristique

volumes:
  mongodb-data:
