name: CI - Test Parc Sauvage

on:
  push:
    branches: [ "main", "Workflow", "Staging"]
  pull_request:
    branches: [ "main", "Workflow", "Staging"]

jobs:
  test-node:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: parcSauvage
        run: npm install

      - name: Run tests
        working-directory: parcSauvage
        run: npm run testSauvage
