name: CI - Docker Parc Sauvage

on:
  push:
    branches: ["main", "Workflow", "Staging"]
  pull_request:
    paths:
      - 'parcSauvage/**'
    branches: ["main", "Workflow", "Staging"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image for Parc Sauvage
        working-directory: parcSauvage
        run: docker compose up --build -d