name: CI - docker Parc Sauvage

on:
  push:
    branches: [ "main", "Workflow" ]
  pull_request:
    branches: [ "main", "Workflow" ]

jobs:
  test-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and run parc-sauvage service
        run: docker compose up --build

